# Copyright 2023 The GenoTools Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Old-vs-new behavioral parity tests.

The whole point of the refactor is *identical scientific results*. The existing
golden files were generated by the NEW code, so they only prove self-consistency.
These tests run the PRE-REFACTOR CLI (from .venv-stable) and the NEW CLI on the
same input and assert the outputs match on sample/variant IDs AND genotype
content (via compare_genotypes, not just ID sets), plus GWAS association tables
and genomic-inflation lambda.

They skip cleanly when .venv-stable is absent. To enable:

    bash tests/scripts/setup_stable_venv.sh        # installs old genotools

See REFACTOR_HARDENING.md for the parity workflow.
"""

import shutil
import subprocess
import sys
from pathlib import Path

import pandas as pd
import pytest

from tests.regression.compare import (
    compare_pfiles,
    compare_genotypes,
    find_gwas_output,
    _lambda_gc,
    _resolve_plink2,
)

REPO_ROOT = Path(__file__).resolve().parents[2]

# Per-step flag spelling: token -> (old_flag, new_flag). Single-word steps
# (haplotype, ld, pca, gwas) are spelled the same in both CLIs; the multi-word
# ones (case_control) and the persist-output flag differ (underscore vs hyphen).
_STEP_FLAGS = {
    "callrate": ("--callrate", "--callrate"),
    "sex": ("--sex", "--sex"),
    "het": ("--het", "--het"),
    "geno": ("--geno", "--geno"),
    "case_control": ("--case_control", "--case-control"),
    "haplotype": ("--haplotype", "--haplotype"),
    "hwe": ("--hwe", "--hwe"),
    "ld": ("--ld", "--ld"),
    "all_sample": ("--all_sample", "--all-sample"),
    "all_variant": ("--all_variant", "--all-variant"),
    "pca": ("--pca", "--pca"),
    "gwas": ("--gwas", "--gwas"),
}

# Explicit values appended after a flag (identical for both CLIs). The old CLI's
# --ld indexes args['ld'][0..2], so bare --ld would IndexError there; pass all
# three values so both command lines are unambiguous and identical.
_STEP_ARGS = {"ld": ["50", "5", "0.5"]}

_OLD_PERSIST = "--full_output"  # old CLI spelling
_NEW_PERSIST = "--full-output"  # new CLI spelling


def _run(cmd: list[str], cwd: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=600)


def _old_cmd(stable_bin: Path, geno: Path, out: Path, tokens: list[str]) -> list[str]:
    cmd = [str(stable_bin), "--pfile", str(geno), "--out", str(out)]
    for token in tokens:
        cmd.append(_STEP_FLAGS[token][0])
        cmd.extend(_STEP_ARGS.get(token, []))
    cmd.append(_OLD_PERSIST)
    return cmd


def _new_cmd(geno: Path, out: Path, tokens: list[str]) -> list[str]:
    cmd = [sys.executable, "-m", "genotools", "--pfile", str(geno), "--out", str(out)]
    for token in tokens:
        cmd.append(_STEP_FLAGS[token][1])
        cmd.extend(_STEP_ARGS.get(token, []))
    cmd.append(_NEW_PERSIST)
    return cmd


def _run_both(
    stable_bin: Path, geno: Path, tmp_path: Path, tokens: list[str]
) -> tuple[Path, Path]:
    """Run old and new CLIs with the same steps; return (old_out, new_out).

    Asserts each CLI produced pfile output (fails loudly with captured output
    otherwise).
    """
    old_out = tmp_path / "old"
    new_out = tmp_path / "new"

    old_res = _run(_old_cmd(stable_bin, geno, old_out, tokens))
    new_res = _run(_new_cmd(geno, new_out, tokens), cwd=str(REPO_ROOT))

    assert old_out.with_suffix(".pgen").exists(), (
        f"Old CLI produced no output for {tokens}.\n"
        f"STDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_out.with_suffix(".pgen").exists(), (
        f"New CLI produced no output for {tokens}.\n"
        f"STDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )
    return old_out, new_out


def _require_parity_env(stable_venv_genotools) -> tuple[Path, str]:
    """Skip unless both .venv-stable and plink2 are available."""
    if stable_venv_genotools is None:
        pytest.skip(
            "No .venv-stable found. Build it with: "
            "bash tests/scripts/setup_stable_venv.sh"
        )
    plink2 = _resolve_plink2()
    if plink2 is None:
        pytest.skip("plink2 not available for genotype-content comparison")
    return stable_venv_genotools, plink2


def _assert_pfile_and_genotype_parity(old_out: Path, new_out: Path, plink2: str) -> None:
    id_result = compare_pfiles(old_out, new_out)
    assert id_result.equal, f"Sample/variant IDs differ: {id_result.message}"

    geno_result = compare_genotypes(old_out, new_out, plink2_exec=plink2)
    assert geno_result.equal, (
        f"Genotype content differs between old and new: {geno_result.message}\n"
        f"Mismatched variants (first 10): {geno_result.mismatched_variants[:10]}"
    )


def test_old_vs_new_qc_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """Same-spelled QC steps must produce identical output (IDs + genotypes)."""
    stable_bin, plink2 = _require_parity_env(stable_venv_genotools)
    old_out, new_out = _run_both(
        stable_bin, test_geno_path, tmp_path, ["callrate", "sex", "het", "geno", "hwe"]
    )
    _assert_pfile_and_genotype_parity(old_out, new_out, plink2)


@pytest.mark.parametrize("step", ["case_control", "haplotype", "ld"])
def test_old_vs_new_multiword_qc_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
    step: str,
) -> None:
    """Multi-word variant QC steps must be parity-equal despite flag-spelling
    differences (old --case_control vs new --case-control, etc.)."""
    stable_bin, plink2 = _require_parity_env(stable_venv_genotools)
    old_out, new_out = _run_both(stable_bin, test_geno_path, tmp_path, [step])
    _assert_pfile_and_genotype_parity(old_out, new_out, plink2)


def test_old_vs_new_full_pipeline_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """--all_sample --all_variant must be parity-equal end to end."""
    stable_bin, plink2 = _require_parity_env(stable_venv_genotools)
    old_out, new_out = _run_both(
        stable_bin, test_geno_path, tmp_path, ["all_sample", "all_variant"]
    )
    _assert_pfile_and_genotype_parity(old_out, new_out, plink2)


def _read_add_results(glm_path: Path) -> pd.DataFrame:
    """Read a PLINK2 --glm table, restricted to the additive (ADD) test."""
    df = pd.read_csv(glm_path, sep=r"\s+", dtype={"#CHROM": str}, low_memory=False)
    if "TEST" in df.columns:
        df = df[df["TEST"] == "ADD"]
    return df


def test_old_vs_new_gwas_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """Old and new --pca --gwas must run and agree on the association output.

    Asserts the strongest invariants that hold today:
      * both CLIs produce a --glm results file (the new CLI produced NONE before
        the --glm-tokenization fix),
      * the same set of variants is tested,
      * the genomic-inflation lambda agrees within a small tolerance.

    Per-variant p-values are NOT asserted equal: the new PCA pruning excludes
    high-LD/MHC regions (`--exclude range`) that the old code left in
    (`--exclude`, a no-op on a ranges file), so the PCA covariates -- and hence
    every GWAS p-value -- differ slightly. That divergence is a *flagged*
    old-vs-new discrepancy documented in REFACTOR_HARDENING.md for a deliberate
    maintainer decision; it is not silently asserted away here.
    """
    stable_bin, _ = _require_parity_env(stable_venv_genotools)

    # Copy the input into tmp: GWAS writes {input}.pheno next to the input, so
    # running against the tracked synthetic data would pollute it.
    geno = tmp_path / "input"
    for ext in (".pgen", ".pvar", ".psam"):
        shutil.copy2(test_geno_path.with_suffix(ext), geno.with_suffix(ext))

    old_out = tmp_path / "old"
    new_out = tmp_path / "new"
    old_res = _run(_old_cmd(stable_bin, geno, old_out, ["pca", "gwas"]))
    new_res = _run(_new_cmd(geno, new_out, ["pca", "gwas"]), cwd=str(REPO_ROOT))

    old_glm = find_gwas_output(old_out)
    new_glm = find_gwas_output(new_out)
    assert old_glm is not None, (
        f"Old CLI produced no GWAS output.\n"
        f"STDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_glm is not None, (
        f"New CLI produced no GWAS output.\n"
        f"STDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )

    old_add = _read_add_results(old_glm)
    new_add = _read_add_results(new_glm)

    old_ids = set(old_add["ID"])
    new_ids = set(new_add["ID"])
    assert old_ids == new_ids, (
        "GWAS tested different variant sets: "
        f"old-only {len(old_ids - new_ids)}, new-only {len(new_ids - old_ids)}"
    )

    lambda_old = _lambda_gc(old_add["P"])
    lambda_new = _lambda_gc(new_add["P"])
    assert abs(lambda_old - lambda_new) <= 0.05, (
        f"Genomic-inflation lambda differs beyond tolerance: "
        f"old={lambda_old:.5f}, new={lambda_new:.5f}"
    )
