# Copyright 2023 The GenoTools Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Old-vs-new behavioral parity tests.

The whole point of the refactor is *identical scientific results*. The existing
golden files were generated by the NEW code, so they only prove self-consistency.
These tests run the PRE-REFACTOR CLI (from .venv-stable) and the NEW CLI on the
same input and assert the outputs match on sample/variant IDs AND genotype
content (via compare_genotypes, not just ID sets).

They skip cleanly when .venv-stable is absent. To enable:

    bash tests/scripts/setup_stable_venv.sh        # installs old genotools

See REFACTOR_HARDENING.md for the parity workflow.
"""

import subprocess
import sys
from pathlib import Path

import pytest

from tests.regression.compare import (
    compare_pfiles,
    compare_genotypes,
    _resolve_plink2,
)

REPO_ROOT = Path(__file__).resolve().parents[2]

# QC step flags spelled identically in BOTH the old and new CLIs. The
# persist-output flag differs (old: --full_output, new: --full-output) and is
# appended per-CLI below.
COMMON_QC_FLAGS = ["--callrate", "--sex", "--het", "--geno", "--hwe"]


def _run(cmd: list[str], cwd: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def test_old_vs_new_qc_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """Old and new CLIs must produce identical QC output (IDs + genotypes)."""
    if stable_venv_genotools is None:
        pytest.skip(
            "No .venv-stable found. Build it with: "
            "bash tests/scripts/setup_stable_venv.sh"
        )

    plink2 = _resolve_plink2()
    if plink2 is None:
        pytest.skip("plink2 not available for genotype-content comparison")

    old_out = tmp_path / "old"
    new_out = tmp_path / "new"

    old_cmd = [
        str(stable_venv_genotools),
        "--pfile", str(test_geno_path),
        "--out", str(old_out),
        *COMMON_QC_FLAGS,
        "--full_output",  # old CLI spelling
    ]
    new_cmd = [
        sys.executable, "-m", "genotools",
        "--pfile", str(test_geno_path),
        "--out", str(new_out),
        *COMMON_QC_FLAGS,
        "--full-output",  # new CLI spelling
    ]

    old_res = _run(old_cmd)
    new_res = _run(new_cmd, cwd=str(REPO_ROOT))

    assert old_out.with_suffix(".pgen").exists(), (
        f"Old CLI produced no output.\nSTDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_out.with_suffix(".pgen").exists(), (
        f"New CLI produced no output.\nSTDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )

    id_result = compare_pfiles(old_out, new_out)
    assert id_result.equal, f"Sample/variant IDs differ: {id_result.message}"

    geno_result = compare_genotypes(old_out, new_out, plink2_exec=plink2)
    assert geno_result.equal, (
        f"Genotype content differs between old and new: {geno_result.message}\n"
        f"Mismatched variants (first 10): {geno_result.mismatched_variants[:10]}"
    )
