# Copyright 2023 The GenoTools Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Old-vs-new behavioral parity tests.

The whole point of the refactor is *identical scientific results*. The existing
golden files were generated by the NEW code, so they only prove self-consistency.
These tests run the PRE-REFACTOR CLI (from .venv-stable) and the NEW CLI on the
same input and assert the outputs match on sample/variant IDs AND genotype
content (via compare_genotypes, not just ID sets), plus GWAS association tables
and genomic-inflation lambda.

They skip cleanly when .venv-stable is absent. To enable:

    bash tests/scripts/setup_stable_venv.sh        # installs old genotools

See REFACTOR.md for the parity workflow.
"""

import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

from tests.regression.compare import (
    compare_pfiles,
    compare_genotypes,
    compare_gwas,
    find_gwas_output,
    _lambda_gc,
    _resolve_plink2,
)

REPO_ROOT = Path(__file__).resolve().parents[2]

# Per-step flag spelling: token -> (old_flag, new_flag). Single-word steps
# (haplotype, ld, pca, gwas) are spelled the same in both CLIs; the multi-word
# ones (case_control) and the persist-output flag differ (underscore vs hyphen).
_STEP_FLAGS = {
    "callrate": ("--callrate", "--callrate"),
    "sex": ("--sex", "--sex"),
    "het": ("--het", "--het"),
    "geno": ("--geno", "--geno"),
    "case_control": ("--case_control", "--case-control"),
    "haplotype": ("--haplotype", "--haplotype"),
    "hwe": ("--hwe", "--hwe"),
    "ld": ("--ld", "--ld"),
    "all_sample": ("--all_sample", "--all-sample"),
    "all_variant": ("--all_variant", "--all-variant"),
    "pca": ("--pca", "--pca"),
    "gwas": ("--gwas", "--gwas"),
}

# Explicit values appended after a flag (identical for both CLIs). The old CLI's
# --ld indexes args['ld'][0..2], so bare --ld would IndexError there; pass all
# three values so both command lines are unambiguous and identical.
_STEP_ARGS = {"ld": ["50", "5", "0.5"]}

_OLD_PERSIST = "--full_output"  # old CLI spelling
_NEW_PERSIST = "--full-output"  # new CLI spelling


def _run(cmd: list[str], cwd: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=600)


def _old_cmd(stable_bin: Path, geno: Path, out: Path, tokens: list[str]) -> list[str]:
    cmd = [str(stable_bin), "--pfile", str(geno), "--out", str(out)]
    for token in tokens:
        cmd.append(_STEP_FLAGS[token][0])
        cmd.extend(_STEP_ARGS.get(token, []))
    cmd.append(_OLD_PERSIST)
    return cmd


def _new_cmd(geno: Path, out: Path, tokens: list[str]) -> list[str]:
    cmd = [sys.executable, "-m", "genotools", "--pfile", str(geno), "--out", str(out)]
    for token in tokens:
        cmd.append(_STEP_FLAGS[token][1])
        cmd.extend(_STEP_ARGS.get(token, []))
    cmd.append(_NEW_PERSIST)
    return cmd


def _run_both(
    stable_bin: Path, geno: Path, tmp_path: Path, tokens: list[str]
) -> tuple[Path, Path]:
    """Run old and new CLIs with the same steps; return (old_out, new_out).

    Asserts each CLI produced pfile output (fails loudly with captured output
    otherwise).
    """
    old_out = tmp_path / "old"
    new_out = tmp_path / "new"

    old_res = _run(_old_cmd(stable_bin, geno, old_out, tokens))
    new_res = _run(_new_cmd(geno, new_out, tokens), cwd=str(REPO_ROOT))

    assert old_out.with_suffix(".pgen").exists(), (
        f"Old CLI produced no output for {tokens}.\n"
        f"STDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_out.with_suffix(".pgen").exists(), (
        f"New CLI produced no output for {tokens}.\n"
        f"STDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )
    return old_out, new_out


def _require_parity_env(stable_venv_genotools) -> tuple[Path, str]:
    """Skip unless both .venv-stable and plink2 are available."""
    if stable_venv_genotools is None:
        pytest.skip(
            "No .venv-stable found. Build it with: "
            "bash tests/scripts/setup_stable_venv.sh"
        )
    plink2 = _resolve_plink2()
    if plink2 is None:
        pytest.skip("plink2 not available for genotype-content comparison")
    return stable_venv_genotools, plink2


def _assert_pfile_and_genotype_parity(old_out: Path, new_out: Path, plink2: str) -> None:
    id_result = compare_pfiles(old_out, new_out)
    assert id_result.equal, f"Sample/variant IDs differ: {id_result.message}"

    geno_result = compare_genotypes(old_out, new_out, plink2_exec=plink2)
    assert geno_result.equal, (
        f"Genotype content differs between old and new: {geno_result.message}\n"
        f"Mismatched variants (first 10): {geno_result.mismatched_variants[:10]}"
    )


def test_old_vs_new_qc_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """Same-spelled QC steps must produce identical output (IDs + genotypes)."""
    stable_bin, plink2 = _require_parity_env(stable_venv_genotools)
    old_out, new_out = _run_both(
        stable_bin, test_geno_path, tmp_path, ["callrate", "sex", "het", "geno", "hwe"]
    )
    _assert_pfile_and_genotype_parity(old_out, new_out, plink2)


@pytest.mark.parametrize("step", ["case_control", "haplotype", "ld"])
def test_old_vs_new_multiword_qc_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
    step: str,
) -> None:
    """Multi-word variant QC steps must be parity-equal despite flag-spelling
    differences (old --case_control vs new --case-control, etc.)."""
    stable_bin, plink2 = _require_parity_env(stable_venv_genotools)
    old_out, new_out = _run_both(stable_bin, test_geno_path, tmp_path, [step])
    _assert_pfile_and_genotype_parity(old_out, new_out, plink2)


def test_old_vs_new_full_pipeline_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """--all_sample --all_variant must be parity-equal end to end."""
    stable_bin, plink2 = _require_parity_env(stable_venv_genotools)
    old_out, new_out = _run_both(
        stable_bin, test_geno_path, tmp_path, ["all_sample", "all_variant"]
    )
    _assert_pfile_and_genotype_parity(old_out, new_out, plink2)


def _read_add_results(glm_path: Path) -> pd.DataFrame:
    """Read a PLINK2 --glm table, restricted to the additive (ADD) test."""
    df = pd.read_csv(glm_path, sep=r"\s+", dtype={"#CHROM": str}, low_memory=False)
    if "TEST" in df.columns:
        df = df[df["TEST"] == "ADD"]
    return df


def test_old_vs_new_gwas_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """Old and new --pca --gwas must run and agree on the association output.

    Asserts the strongest invariants that hold today:
      * both CLIs produce a --glm results file (the new CLI produced NONE before
        the --glm-tokenization fix),
      * the same set of variants is tested,
      * the genomic-inflation lambda agrees within a small tolerance.

    Per-variant p-values are NOT asserted equal: the new PCA pruning excludes
    high-LD/MHC regions (`--exclude range`) that the old code left in
    (`--exclude`, a no-op on a ranges file), so the PCA covariates -- and hence
    every GWAS p-value -- differ slightly. That divergence is a *ratified,
    intentional* correctness fix (decision B in REFACTOR.md): excluding
    those regions before PCA is standard practice, so GWAS parity is asserted at
    the tested-variant-set + lambda level, not per-variant, by design.
    """
    stable_bin, _ = _require_parity_env(stable_venv_genotools)

    # Copy the input into tmp: GWAS writes {input}.pheno next to the input, so
    # running against the tracked synthetic data would pollute it.
    geno = tmp_path / "input"
    for ext in (".pgen", ".pvar", ".psam"):
        shutil.copy2(test_geno_path.with_suffix(ext), geno.with_suffix(ext))

    old_out = tmp_path / "old"
    new_out = tmp_path / "new"
    old_res = _run(_old_cmd(stable_bin, geno, old_out, ["pca", "gwas"]))
    new_res = _run(_new_cmd(geno, new_out, ["pca", "gwas"]), cwd=str(REPO_ROOT))

    old_glm = find_gwas_output(old_out)
    new_glm = find_gwas_output(new_out)
    assert old_glm is not None, (
        f"Old CLI produced no GWAS output.\n"
        f"STDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_glm is not None, (
        f"New CLI produced no GWAS output.\n"
        f"STDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )

    old_add = _read_add_results(old_glm)
    new_add = _read_add_results(new_glm)

    old_ids = set(old_add["ID"])
    new_ids = set(new_add["ID"])
    assert old_ids == new_ids, (
        "GWAS tested different variant sets: "
        f"old-only {len(old_ids - new_ids)}, new-only {len(new_ids - old_ids)}"
    )

    lambda_old = _lambda_gc(old_add["P"])
    lambda_new = _lambda_gc(new_add["P"])
    assert abs(lambda_old - lambda_new) <= 0.05, (
        f"Genomic-inflation lambda differs beyond tolerance: "
        f"old={lambda_old:.5f}, new={lambda_new:.5f}"
    )


def _find_eigenvec(out_prefix: Path) -> Path | None:
    """Locate a PLINK2 .eigenvec file for a run output prefix."""
    out_prefix = Path(out_prefix)
    matches = sorted(out_prefix.parent.glob(f"{out_prefix.name}*.eigenvec"))
    return matches[0] if matches else None


def _count_pc_columns(eigenvec_path: Path) -> int:
    """Count the PC columns (PC1, PC2, ...) in a PLINK2 .eigenvec header."""
    with open(eigenvec_path) as f:
        header = f.readline().strip().split("\t")
    return sum(1 for col in header if col.upper().startswith("PC"))


def test_old_vs_new_pca_ncount_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """A non-default `--pca N` must produce an N-PC eigenvec in BOTH CLIs.

    The new runner previously dropped the requested PC count and PLINK2 always
    wrote the default 10 PCs; the old CLI honored it. This asserts they now
    agree on the eigenvector dimensionality for a non-default count (20).
    """
    stable_bin, _ = _require_parity_env(stable_venv_genotools)

    n_pcs = 20
    old_out = tmp_path / "old"
    new_out = tmp_path / "new"
    old_res = _run(
        [str(stable_bin), "--pfile", str(test_geno_path), "--out", str(old_out),
         "--pca", str(n_pcs)]
    )
    new_res = _run(
        [sys.executable, "-m", "genotools", "--pfile", str(test_geno_path),
         "--out", str(new_out), "--pca", str(n_pcs)],
        cwd=str(REPO_ROOT),
    )

    old_ev = _find_eigenvec(old_out)
    new_ev = _find_eigenvec(new_out)
    assert old_ev is not None, (
        f"Old CLI produced no eigenvec.\nSTDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_ev is not None, (
        f"New CLI produced no eigenvec.\nSTDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )

    old_n = _count_pc_columns(old_ev)
    new_n = _count_pc_columns(new_ev)
    assert old_n == n_pcs, f"Old CLI wrote {old_n} PCs, expected {n_pcs}"
    assert new_n == n_pcs, f"New CLI wrote {new_n} PCs, expected {n_pcs} (was silently 10)"


def _write_covariate_file(psam_path: Path, covar_path: Path) -> str:
    """Write an external covariate file (#FID IID COV1 COV2) for a psam's samples.

    Returns the comma-separated covariate names. Values are deterministic (fixed
    seed) so the same file feeds both CLIs and the run is reproducible.
    """
    psam = pd.read_csv(psam_path, sep=r"\s+")
    fid_col = "#FID" if "#FID" in psam.columns else "#IID"
    rng = np.random.default_rng(42)
    n = len(psam)
    cov = pd.DataFrame({
        "#FID": psam[fid_col].to_numpy(),
        "IID": psam["IID"].to_numpy(),
        "COV1": rng.normal(size=n),
        "COV2": rng.normal(size=n),
    })
    cov.to_csv(covar_path, sep="\t", index=False)
    return "COV1,COV2"


def test_old_vs_new_gwas_external_covars_parity(
    stable_venv_genotools,
    test_geno_path: Path,
    tmp_path: Path,
) -> None:
    """External `--covars`/`--covar-names` must reach GWAS identically in both CLIs.

    The new runner previously dropped `--covars`/`--covar-names`, so GWAS fell
    back to the PCA eigenvectors as covariates while the old CLI used the external
    file -- different covariates, so p-values diverged. With `--pca --gwas
    --covars`, BOTH CLIs discard the PCA eigenvectors and use the external file
    (PLINK2's `--covar`), so decision B's PCA-region-exclusion divergence does NOT
    apply here: the GWAS uses byte-identical `--glm` options and the same covariate
    file, so per-variant p-values must agree tightly. This proves the external
    covariates are actually used (and used identically) by the new CLI.
    """
    stable_bin, _ = _require_parity_env(stable_venv_genotools)

    # Copy input into tmp: GWAS writes {input}.pheno next to the input.
    geno = tmp_path / "input"
    for ext in (".pgen", ".pvar", ".psam"):
        shutil.copy2(test_geno_path.with_suffix(ext), geno.with_suffix(ext))

    covar_file = tmp_path / "external.cov"
    covar_names = _write_covariate_file(geno.with_suffix(".psam"), covar_file)

    old_out = tmp_path / "old"
    new_out = tmp_path / "new"
    old_res = _run(
        [str(stable_bin), "--pfile", str(geno), "--out", str(old_out),
         "--pca", "10", "--gwas", "--covars", str(covar_file),
         "--covar_names", covar_names]
    )
    new_res = _run(
        [sys.executable, "-m", "genotools", "--pfile", str(geno), "--out", str(new_out),
         "--pca", "10", "--gwas", "--covars", str(covar_file),
         "--covar-names", covar_names],
        cwd=str(REPO_ROOT),
    )

    old_glm = find_gwas_output(old_out)
    new_glm = find_gwas_output(new_out)
    assert old_glm is not None, (
        f"Old CLI produced no GWAS output.\nSTDOUT:\n{old_res.stdout}\nSTDERR:\n{old_res.stderr}"
    )
    assert new_glm is not None, (
        f"New CLI produced no GWAS output.\nSTDOUT:\n{new_res.stdout}\nSTDERR:\n{new_res.stderr}"
    )

    # External covars are used identically by both -> per-variant p-values agree.
    result = compare_gwas(old_out, new_out, p_tolerance=1e-6, lambda_tolerance=1e-3)
    assert result.equal, (
        f"GWAS with external covariates diverged old-vs-new: {result.message}\n"
        f"If the new CLI dropped --covars it would fall back to PCA covariates and "
        f"diverge here. First mismatches: {result.mismatched_variants[:10]}"
    )
